//! Bulk operations for Dividend entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDividendDto;
use crate::application::service::DividendService;
use crate::domain::entity::Dividend;

/// Bulk operation handler for Dividend entities.
///
/// Wraps `DividendService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DividendBulkService = GenericBulkService<Dividend, CreateDividendDto, DividendService>;

// <<< CUSTOM
// END CUSTOM
