//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod dividend_bulk;
pub mod share_class_bulk;
pub mod shareholder_bulk;
pub mod share_transaction_bulk;

pub use dividend_bulk::DividendBulkService;
pub use share_class_bulk::ShareClassBulkService;
pub use shareholder_bulk::ShareholderBulkService;
pub use share_transaction_bulk::ShareTransactionBulkService;

// <<< CUSTOM
// END CUSTOM
