//! Bulk operations for ShareTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateShareTransactionDto;
use crate::application::service::ShareTransactionService;
use crate::domain::entity::ShareTransaction;

/// Bulk operation handler for ShareTransaction entities.
///
/// Wraps `ShareTransactionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ShareTransactionBulkService = GenericBulkService<ShareTransaction, CreateShareTransactionDto, ShareTransactionService>;

// <<< CUSTOM
// END CUSTOM
