//! Bulk operations for ShareClass entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateShareClassDto;
use crate::application::service::ShareClassService;
use crate::domain::entity::ShareClass;

/// Bulk operation handler for ShareClass entities.
///
/// Wraps `ShareClassService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ShareClassBulkService = GenericBulkService<ShareClass, CreateShareClassDto, ShareClassService>;

// <<< CUSTOM
// END CUSTOM
