//! Dividend DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Dividend;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DividendStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Dividend
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDividendDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "share_class_id")]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "declaration_date")]
    pub declaration_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payment_date")]
    pub payment_date: Option<NaiveDate>,
    #[serde(alias = "per_share_amount")]
    pub per_share_amount: Decimal,
    #[serde(alias = "shares_outstanding")]
    pub shares_outstanding: Decimal,
    #[serde(alias = "total_amount")]
    pub total_amount: Decimal,
    pub status: DividendStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "retained_earnings_account_id")]
    pub retained_earnings_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "dividend_payable_account_id")]
    pub dividend_payable_account_id: Uuid,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Dividend
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDividendDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "share_class_id")]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "declaration_date")]
    pub declaration_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "payment_date")]
    pub payment_date: Option<NaiveDate>,
    #[serde(alias = "per_share_amount")]
    pub per_share_amount: Decimal,
    #[serde(alias = "shares_outstanding")]
    pub shares_outstanding: Decimal,
    #[serde(alias = "total_amount")]
    pub total_amount: Decimal,
    pub status: DividendStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "retained_earnings_account_id")]
    pub retained_earnings_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "dividend_payable_account_id")]
    pub dividend_payable_account_id: Uuid,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Dividend
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDividendDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "share_class_id")]
    pub share_class_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "declaration_date")]
    pub declaration_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "payment_date")]
    pub payment_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "per_share_amount")]
    pub per_share_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "shares_outstanding")]
    pub shares_outstanding: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "total_amount")]
    pub total_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DividendStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "retained_earnings_account_id")]
    pub retained_earnings_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "dividend_payable_account_id")]
    pub dividend_payable_account_id: Option<Uuid>,
}

impl PatchDividendDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.share_class_id.is_some() || self.declaration_date.is_some() || self.payment_date.is_some() || self.per_share_amount.is_some() || self.shares_outstanding.is_some() || self.total_amount.is_some() || self.status.is_some() || self.retained_earnings_account_id.is_some() || self.dividend_payable_account_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Dividend entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DividendResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub declaration_date: NaiveDate,
    pub payment_date: Option<NaiveDate>,
    pub per_share_amount: Decimal,
    pub shares_outstanding: Decimal,
    pub total_amount: Decimal,
    pub status: DividendStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub retained_earnings_account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub dividend_payable_account_id: Uuid,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Dividend entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DividendListResponseDto {
    /// List of items
    pub items: Vec<DividendResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DividendListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DividendResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DividendSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub share_class_id: Uuid,
    pub declaration_date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Dividend> for DividendResponseDto {
    fn from(entity: Dividend) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            share_class_id: entity.share_class_id,
            declaration_date: entity.declaration_date,
            payment_date: entity.payment_date,
            per_share_amount: entity.per_share_amount,
            shares_outstanding: entity.shares_outstanding,
            total_amount: entity.total_amount,
            status: entity.status,
            retained_earnings_account_id: entity.retained_earnings_account_id,
            dividend_payable_account_id: entity.dividend_payable_account_id,
            metadata: entity.metadata,
        }
    }
}

impl From<Dividend> for DividendSummaryDto {
    fn from(entity: Dividend) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            share_class_id: entity.share_class_id,
            declaration_date: entity.declaration_date,
            created_at,
        }
    }
}

impl From<CreateDividendDto> for Dividend {
    fn from(dto: CreateDividendDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            share_class_id: dto.share_class_id,
            declaration_date: dto.declaration_date,
            payment_date: dto.payment_date,
            per_share_amount: dto.per_share_amount,
            shares_outstanding: dto.shares_outstanding,
            total_amount: dto.total_amount,
            status: dto.status,
            retained_earnings_account_id: dto.retained_earnings_account_id,
            dividend_payable_account_id: dto.dividend_payable_account_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Dividend> for DividendResponseDto {
    fn from(entity: &Dividend) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            share_class_id: entity.share_class_id.clone(),
            declaration_date: entity.declaration_date.clone(),
            payment_date: entity.payment_date.clone(),
            per_share_amount: entity.per_share_amount.clone(),
            shares_outstanding: entity.shares_outstanding.clone(),
            total_amount: entity.total_amount.clone(),
            status: entity.status.clone(),
            retained_earnings_account_id: entity.retained_earnings_account_id.clone(),
            dividend_payable_account_id: entity.dividend_payable_account_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDividendDto> for Dividend {
    fn from_create_dto(dto: CreateDividendDto) -> backbone_core::ServiceResult<Self> {
        Ok(Dividend::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDividendDto> for Dividend {
    fn apply_update(mut self, dto: UpdateDividendDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.share_class_id = dto.share_class_id;
        self.declaration_date = dto.declaration_date;
        self.payment_date = dto.payment_date;
        self.per_share_amount = dto.per_share_amount;
        self.shares_outstanding = dto.shares_outstanding;
        self.total_amount = dto.total_amount;
        self.status = dto.status;
        self.retained_earnings_account_id = dto.retained_earnings_account_id;
        self.dividend_payable_account_id = dto.dividend_payable_account_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Dividend here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
