//! ShareTransaction DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ShareTransaction;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ShareTxnType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ShareTransaction
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateShareTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "share_class_id")]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "shareholder_id")]
    pub shareholder_id: Uuid,
    #[serde(alias = "txn_type")]
    pub txn_type: ShareTxnType,
    pub quantity: Decimal,
    #[serde(alias = "price_per_share")]
    pub price_per_share: Decimal,
    pub amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "counterparty_shareholder_id")]
    pub counterparty_shareholder_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "transfer_group_id")]
    pub transfer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posting_reference")]
    pub posting_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "txn_date")]
    pub txn_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "gl_posted")]
    pub gl_posted: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ShareTransaction
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateShareTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "share_class_id")]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "shareholder_id")]
    pub shareholder_id: Uuid,
    #[serde(alias = "txn_type")]
    pub txn_type: ShareTxnType,
    pub quantity: Decimal,
    #[serde(alias = "price_per_share")]
    pub price_per_share: Decimal,
    pub amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "counterparty_shareholder_id")]
    pub counterparty_shareholder_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "transfer_group_id")]
    pub transfer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posting_reference")]
    pub posting_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "txn_date")]
    pub txn_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "gl_posted")]
    pub gl_posted: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ShareTransaction
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchShareTransactionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "share_class_id")]
    pub share_class_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "shareholder_id")]
    pub shareholder_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "txn_type")]
    pub txn_type: Option<ShareTxnType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "price_per_share")]
    pub price_per_share: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "counterparty_shareholder_id")]
    pub counterparty_shareholder_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "transfer_group_id")]
    pub transfer_group_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 80)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_reference")]
    pub posting_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "txn_date")]
    pub txn_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "gl_posted")]
    pub gl_posted: Option<bool>,
}

impl PatchShareTransactionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.share_class_id.is_some() || self.shareholder_id.is_some() || self.txn_type.is_some() || self.quantity.is_some() || self.price_per_share.is_some() || self.amount.is_some() || self.counterparty_shareholder_id.is_some() || self.transfer_group_id.is_some() || self.posting_reference.is_some() || self.txn_date.is_some() || self.gl_posted.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ShareTransaction entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShareTransactionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub share_class_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub shareholder_id: Uuid,
    pub txn_type: ShareTxnType,
    pub quantity: Decimal,
    pub price_per_share: Decimal,
    pub amount: Decimal,
    pub counterparty_shareholder_id: Option<Uuid>,
    pub transfer_group_id: Option<Uuid>,
    pub posting_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub txn_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub gl_posted: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ShareTransaction entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShareTransactionListResponseDto {
    /// List of items
    pub items: Vec<ShareTransactionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ShareTransactionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ShareTransactionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ShareTransactionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub share_class_id: Uuid,
    pub shareholder_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ShareTransaction> for ShareTransactionResponseDto {
    fn from(entity: ShareTransaction) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            share_class_id: entity.share_class_id,
            shareholder_id: entity.shareholder_id,
            txn_type: entity.txn_type,
            quantity: entity.quantity,
            price_per_share: entity.price_per_share,
            amount: entity.amount,
            counterparty_shareholder_id: entity.counterparty_shareholder_id,
            transfer_group_id: entity.transfer_group_id,
            posting_reference: entity.posting_reference,
            txn_date: entity.txn_date,
            gl_posted: entity.gl_posted,
            metadata: entity.metadata,
        }
    }
}

impl From<ShareTransaction> for ShareTransactionSummaryDto {
    fn from(entity: ShareTransaction) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            share_class_id: entity.share_class_id,
            shareholder_id: entity.shareholder_id,
            created_at,
        }
    }
}

impl From<CreateShareTransactionDto> for ShareTransaction {
    fn from(dto: CreateShareTransactionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            share_class_id: dto.share_class_id,
            shareholder_id: dto.shareholder_id,
            txn_type: dto.txn_type,
            quantity: dto.quantity,
            price_per_share: dto.price_per_share,
            amount: dto.amount,
            counterparty_shareholder_id: dto.counterparty_shareholder_id,
            transfer_group_id: dto.transfer_group_id,
            posting_reference: dto.posting_reference,
            txn_date: dto.txn_date,
            gl_posted: dto.gl_posted,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ShareTransaction> for ShareTransactionResponseDto {
    fn from(entity: &ShareTransaction) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            share_class_id: entity.share_class_id.clone(),
            shareholder_id: entity.shareholder_id.clone(),
            txn_type: entity.txn_type.clone(),
            quantity: entity.quantity.clone(),
            price_per_share: entity.price_per_share.clone(),
            amount: entity.amount.clone(),
            counterparty_shareholder_id: entity.counterparty_shareholder_id.clone(),
            transfer_group_id: entity.transfer_group_id.clone(),
            posting_reference: entity.posting_reference.clone(),
            txn_date: entity.txn_date.clone(),
            gl_posted: entity.gl_posted.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateShareTransactionDto> for ShareTransaction {
    fn from_create_dto(dto: CreateShareTransactionDto) -> backbone_core::ServiceResult<Self> {
        Ok(ShareTransaction::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateShareTransactionDto> for ShareTransaction {
    fn apply_update(mut self, dto: UpdateShareTransactionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.share_class_id = dto.share_class_id;
        self.shareholder_id = dto.shareholder_id;
        self.txn_type = dto.txn_type;
        self.quantity = dto.quantity;
        self.price_per_share = dto.price_per_share;
        self.amount = dto.amount;
        self.counterparty_shareholder_id = dto.counterparty_shareholder_id;
        self.transfer_group_id = dto.transfer_group_id;
        self.posting_reference = dto.posting_reference;
        self.txn_date = dto.txn_date;
        self.gl_posted = dto.gl_posted;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ShareTransaction here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
