//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod dividend_specification;
pub mod share_class_specification;
pub mod shareholder_specification;
pub mod share_transaction_specification;

// <<< CUSTOM
// END CUSTOM
