//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod dividend_domain_policy;
pub mod share_class_domain_policy;
pub mod shareholder_domain_policy;
pub mod share_transaction_domain_policy;

pub use dividend_domain_policy::DividendDomainPolicy;
pub use share_class_domain_policy::ShareClassDomainPolicy;
pub use shareholder_domain_policy::ShareholderDomainPolicy;
pub use share_transaction_domain_policy::ShareTransactionDomainPolicy;

// <<< CUSTOM
// END CUSTOM
