//! Domain policy for ShareClass aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::ShareClass;

/// Domain policy for ShareClass — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<ShareClass>` in the `// <<< CUSTOM` zone.
pub type ShareClassDomainPolicy = PermitAllPolicy<ShareClass>;

// <<< CUSTOM
// END CUSTOM
