//! Application service for Dividend entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `dividend_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDividendDto, UpdateDividendDto};
use crate::domain::entity::Dividend;
use crate::infrastructure::persistence::DividendRepository;

/// Application service for Dividend entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `dividend_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DividendServiceCustom {
///     inner: Arc<DividendService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DividendService = GenericCrudService<
    Dividend,
    CreateDividendDto,
    UpdateDividendDto,
    DividendRepository,
>;

// <<< CUSTOM
// END CUSTOM
