//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod dividend_service;
pub mod share_class_service;
pub mod shareholder_service;
pub mod share_transaction_service;

// <<< CUSTOM
pub mod equity_gl;
pub mod equity_events;
pub mod equity_write_service;
// The write surface, chunked out of equity_write_service.rs. Each is an `impl EquityWriteService` block
// over the vocabulary that stays in `equity_write_service` (so the
// `equity_write_service::{IssueShares, ...}` import paths are unchanged).
pub mod equity_register;
pub mod equity_issue;
pub mod equity_transfer;
pub mod equity_buyback;
pub mod equity_dividend;
pub mod equity_read;
// END CUSTOM

pub use dividend_service::DividendService;
pub use share_class_service::ShareClassService;
pub use shareholder_service::ShareholderService;
pub use share_transaction_service::ShareTransactionService;
// <<< CUSTOM
pub use equity_write_service::{EquityWriteService, EquityError, NewShareClass, NewShareholder, IssueShares, TransferShares, BuybackShares, DeclareDividend, PostOutcome, Holding, Allocation};
pub use equity_events::{EquityEvent, EquityEventSink, LoggingSink};
pub use equity_gl::{AccountingPostEnvelope, GlPostLine, GlPostAck, GlPostRejected, GlPostSink};
// END CUSTOM