//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod dividend_service;
pub mod share_class_service;
pub mod shareholder_service;
pub mod share_transaction_service;

// <<< CUSTOM
pub mod equity_gl;
pub mod equity_events;
pub mod equity_write_service;
// The write surface, chunked out of equity_write_service.rs. Each is an `impl EquityWriteService` block
// over the vocabulary that stays in `equity_write_service` (so the
// `equity_write_service::{IssueShares, ...}` import paths are unchanged).
pub mod equity_register;
pub mod equity_issue;
pub mod equity_transfer;
pub mod equity_buyback;
pub mod equity_dividend;
pub mod equity_read;
// In-tree reference impl of the read contract (gated; not a deployed service).
#[cfg(feature = "unstable-write-service")]
pub mod equity_query_service_impl;
// END CUSTOM

pub use dividend_service::DividendService;
pub use share_class_service::ShareClassService;
pub use shareholder_service::ShareholderService;
pub use share_transaction_service::ShareTransactionService;
// <<< CUSTOM
// The hand-authored cap-table write surface — NOT a committed contract. No in-workspace service composes
// it yet (no `impl` of the read contract, no `EquityWriteService::new` outside tests). Reach it via the
// deep path `application::service::equity_write_service::*` (as the tests do) or opt into the curated
// re-exports below with the `unstable-write-service` feature. The crate's default public surface is
// generic CRUD (see `lib.rs`).
#[cfg(feature = "unstable-write-service")]
pub use equity_write_service::{EquityWriteService, EquityError, NewShareClass, NewShareholder, IssueShares, TransferShares, BuybackShares, DeclareDividend, PostOutcome, Holding, Allocation};
#[cfg(feature = "unstable-write-service")]
pub use equity_events::{EquityEvent, EquityEventSink, LoggingSink};
#[cfg(feature = "unstable-write-service")]
pub use equity_gl::{AccountingPostEnvelope, GlPostLine, GlPostAck, GlPostRejected, GlPostSink};
#[cfg(feature = "unstable-write-service")]
pub use equity_query_service_impl::EquityQueryServiceImpl;
// END CUSTOM