//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod dividend_service;
pub mod share_class_service;
pub mod shareholder_service;
pub mod share_transaction_service;

// <<< CUSTOM
pub mod equity_gl;
pub mod equity_events;
pub mod equity_write_service;
// END CUSTOM

pub use dividend_service::DividendService;
pub use share_class_service::ShareClassService;
pub use shareholder_service::ShareholderService;
pub use share_transaction_service::ShareTransactionService;
// <<< CUSTOM
pub use equity_write_service::{EquityWriteService, EquityError, NewShareClass, NewShareholder, IssueShares, TransferShares, BuybackShares, DeclareDividend, PostOutcome, Holding, Allocation};
pub use equity_events::{EquityEvent, EquityEventSink, LoggingSink};
pub use equity_gl::{AccountingPostEnvelope, GlPostLine, GlPostAck, GlPostRejected, GlPostSink};
// END CUSTOM