//! Application service for Shareholder entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `shareholder_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateShareholderDto, UpdateShareholderDto};
use crate::domain::entity::Shareholder;
use crate::infrastructure::persistence::ShareholderRepository;

/// Application service for Shareholder entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `shareholder_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ShareholderServiceCustom {
///     inner: Arc<ShareholderService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ShareholderService = GenericCrudService<
    Shareholder,
    CreateShareholderDto,
    UpdateShareholderDto,
    ShareholderRepository,
>;

// <<< CUSTOM
// END CUSTOM
