//! Application service for ShareTransaction entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `share_transaction_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateShareTransactionDto, UpdateShareTransactionDto};
use crate::domain::entity::ShareTransaction;
use crate::infrastructure::persistence::ShareTransactionRepository;

/// Application service for ShareTransaction entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `share_transaction_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ShareTransactionServiceCustom {
///     inner: Arc<ShareTransactionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ShareTransactionService = GenericCrudService<
    ShareTransaction,
    CreateShareTransactionDto,
    UpdateShareTransactionDto,
    ShareTransactionRepository,
>;

// <<< CUSTOM
// END CUSTOM
