-- Dividend Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the equity.dividends table.
-- Customize this file to add your initial data.

-- INSERT INTO equity.dividends (
--     id,
--     company_id,
--     share_class_id,
--     declaration_date,
--     payment_date,
--     per_share_amount,
--     shares_outstanding,
--     total_amount,
--     status,
--     retained_earnings_account_id,
--     dividend_payable_account_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO equity.dividends (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

