-- ShareClass Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the equity.share_classes table.
-- Customize this file to add your initial data.

-- INSERT INTO equity.share_classes (
--     id,
--     company_id,
--     code,
--     name,
--     par_value,
--     currency,
--     share_capital_account_id,
--     share_premium_account_id,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO equity.share_classes (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

