-- ShareTransaction Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the equity.share_transactions table.
-- Customize this file to add your initial data.

-- INSERT INTO equity.share_transactions (
--     id,
--     company_id,
--     share_class_id,
--     shareholder_id,
--     txn_type,
--     quantity,
--     price_per_share,
--     amount,
--     counterparty_shareholder_id,
--     transfer_group_id,
--     posting_reference,
--     txn_date,
--     gl_posted,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO equity.share_transactions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

