-- SEED: none
--
-- Share classes belong to a company's own capital structure — par value, currency
-- and the GL accounts each class posts to. Those accounts come from the chart the
-- chart-install verb creates per company.
--
-- The tenancy descriptor anchors this table on a company or branch node, which
-- is the same statement in schema form: there is no tenant-independent row to
-- seed, and a seed run has no company to anchor one to.
