-- Migration: Create dividends table
-- Generated by metaphor-schema

-- Create dividend_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dividend_status') THEN
        CREATE TYPE dividend_status AS ENUM ('declared', 'paid');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS equity;

CREATE TABLE IF NOT EXISTS equity.dividends (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    share_class_id UUID NOT NULL,
    declaration_date DATE NOT NULL,
    payment_date DATE,
    per_share_amount NUMERIC NOT NULL,
    shares_outstanding NUMERIC NOT NULL,
    total_amount NUMERIC NOT NULL,
    status dividend_status NOT NULL DEFAULT 'declared',
    retained_earnings_account_id UUID NOT NULL,
    dividend_payable_account_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_dividends_company_id_share_class_id ON equity.dividends (company_id, share_class_id);

CREATE INDEX IF NOT EXISTS idx_dividends_status ON equity.dividends (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_dividends_metadata_gin ON equity.dividends USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_dividends_metadata_deleted_at ON equity.dividends ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_dividends_metadata_created_at ON equity.dividends ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_dividends_metadata_updated_at ON equity.dividends ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION equity.dividends_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS dividends_insert_audit ON equity.dividends;
CREATE TRIGGER dividends_insert_audit BEFORE INSERT ON equity.dividends
    FOR EACH ROW EXECUTE FUNCTION equity.dividends_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS dividends_update_audit ON equity.dividends;
CREATE TRIGGER dividends_update_audit BEFORE UPDATE ON equity.dividends
    FOR EACH ROW EXECUTE FUNCTION equity.dividends_audit_timestamp();
