-- Audit Triggers Migration for equity module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Dividend (equity.dividends)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION equity.dividends_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS dividends_insert_audit ON equity.dividends;
CREATE TRIGGER dividends_insert_audit BEFORE INSERT ON equity.dividends
    FOR EACH ROW EXECUTE FUNCTION equity.dividends_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS dividends_update_audit ON equity.dividends;
CREATE TRIGGER dividends_update_audit BEFORE UPDATE ON equity.dividends
    FOR EACH ROW EXECUTE FUNCTION equity.dividends_audit_timestamp();

-- ==============================================================================
-- Table: ShareClass (equity.share_classes)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION equity.share_classes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS share_classes_insert_audit ON equity.share_classes;
CREATE TRIGGER share_classes_insert_audit BEFORE INSERT ON equity.share_classes
    FOR EACH ROW EXECUTE FUNCTION equity.share_classes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS share_classes_update_audit ON equity.share_classes;
CREATE TRIGGER share_classes_update_audit BEFORE UPDATE ON equity.share_classes
    FOR EACH ROW EXECUTE FUNCTION equity.share_classes_audit_timestamp();

-- ==============================================================================
-- Table: Shareholder (equity.shareholders)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION equity.shareholders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS shareholders_insert_audit ON equity.shareholders;
CREATE TRIGGER shareholders_insert_audit BEFORE INSERT ON equity.shareholders
    FOR EACH ROW EXECUTE FUNCTION equity.shareholders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS shareholders_update_audit ON equity.shareholders;
CREATE TRIGGER shareholders_update_audit BEFORE UPDATE ON equity.shareholders
    FOR EACH ROW EXECUTE FUNCTION equity.shareholders_audit_timestamp();

-- ==============================================================================
-- Table: ShareTransaction (equity.share_transactions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION equity.share_transactions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS share_transactions_insert_audit ON equity.share_transactions;
CREATE TRIGGER share_transactions_insert_audit BEFORE INSERT ON equity.share_transactions
    FOR EACH ROW EXECUTE FUNCTION equity.share_transactions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS share_transactions_update_audit ON equity.share_transactions;
CREATE TRIGGER share_transactions_update_audit BEFORE UPDATE ON equity.share_transactions
    FOR EACH ROW EXECUTE FUNCTION equity.share_transactions_audit_timestamp();

