-- Company RLS fence for equity module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for equity.dividends
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE equity.dividends ENABLE ROW LEVEL SECURITY;
ALTER TABLE equity.dividends FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dividends_company_isolation ON equity.dividends;
CREATE POLICY dividends_company_isolation ON equity.dividends
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for equity.share_classes
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE equity.share_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE equity.share_classes FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS share_classes_company_isolation ON equity.share_classes;
CREATE POLICY share_classes_company_isolation ON equity.share_classes
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for equity.shareholders
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE equity.shareholders ENABLE ROW LEVEL SECURITY;
ALTER TABLE equity.shareholders FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS shareholders_company_isolation ON equity.shareholders;
CREATE POLICY shareholders_company_isolation ON equity.shareholders
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for equity.share_transactions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE equity.share_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE equity.share_transactions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS share_transactions_company_isolation ON equity.share_transactions;
CREATE POLICY share_transactions_company_isolation ON equity.share_transactions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

