-- Migration: Create share_classes table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS equity;

CREATE TABLE IF NOT EXISTS equity.share_classes (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    par_value NUMERIC NOT NULL,
    currency TEXT NOT NULL,
    share_capital_account_id UUID NOT NULL,
    share_premium_account_id UUID NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_share_classes_company_id_code ON equity.share_classes (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_share_classes_metadata_gin ON equity.share_classes USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_share_classes_metadata_deleted_at ON equity.share_classes ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_share_classes_metadata_created_at ON equity.share_classes ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_share_classes_metadata_updated_at ON equity.share_classes ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION equity.share_classes_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS share_classes_insert_audit ON equity.share_classes;
CREATE TRIGGER share_classes_insert_audit BEFORE INSERT ON equity.share_classes
    FOR EACH ROW EXECUTE FUNCTION equity.share_classes_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS share_classes_update_audit ON equity.share_classes;
CREATE TRIGGER share_classes_update_audit BEFORE UPDATE ON equity.share_classes
    FOR EACH ROW EXECUTE FUNCTION equity.share_classes_audit_timestamp();
