-- Migration: Create share_transactions table
-- Generated by metaphor-schema

-- Create share_txn_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'share_txn_type') THEN
        CREATE TYPE share_txn_type AS ENUM ('issue', 'transfer_in', 'transfer_out', 'buyback');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS equity;

CREATE TABLE IF NOT EXISTS equity.share_transactions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    share_class_id UUID NOT NULL,
    shareholder_id UUID NOT NULL,
    txn_type share_txn_type NOT NULL,
    quantity NUMERIC NOT NULL,
    price_per_share NUMERIC NOT NULL,
    amount NUMERIC NOT NULL,
    counterparty_shareholder_id UUID,
    transfer_group_id UUID,
    posting_reference TEXT,
    txn_date DATE NOT NULL,
    gl_posted BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_share_transactions_company_id_share_class_id_shareholder_id ON equity.share_transactions (company_id, share_class_id, shareholder_id);

CREATE INDEX IF NOT EXISTS idx_share_transactions_transfer_group_id ON equity.share_transactions (transfer_group_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_share_transactions_metadata_gin ON equity.share_transactions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_share_transactions_metadata_deleted_at ON equity.share_transactions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_share_transactions_metadata_created_at ON equity.share_transactions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_share_transactions_metadata_updated_at ON equity.share_transactions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION equity.share_transactions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS share_transactions_insert_audit ON equity.share_transactions;
CREATE TRIGGER share_transactions_insert_audit BEFORE INSERT ON equity.share_transactions
    FOR EACH ROW EXECUTE FUNCTION equity.share_transactions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS share_transactions_update_audit ON equity.share_transactions;
CREATE TRIGGER share_transactions_update_audit BEFORE UPDATE ON equity.share_transactions
    FOR EACH ROW EXECUTE FUNCTION equity.share_transactions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE equity.share_transactions ADD CONSTRAINT fk_share_transactions_share_class_id FOREIGN KEY (share_class_id) REFERENCES equity.share_classes (id);
