-- Enum types for equity module
-- Generated by metaphor-schema

-- Create dividend_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dividend_status') THEN
        CREATE TYPE dividend_status AS ENUM ('declared', 'paid');
    END IF;
END
$$;

-- Create holder_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'holder_type') THEN
        CREATE TYPE holder_type AS ENUM ('individual', 'entity');
    END IF;
END
$$;

-- Create share_txn_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'share_txn_type') THEN
        CREATE TYPE share_txn_type AS ENUM ('issue', 'transfer_in', 'transfer_out', 'buyback');
    END IF;
END
$$;

