//! Domain events for Dividend entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Dividend;

/// Domain events for Dividend — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Dividend>)` variant.
pub type DividendEvent = CrudEvent<Dividend>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Dividend events.
pub type DividendEventPublisher = Arc<dyn CrudEventPublisher<Dividend> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDividendEventPublisher = NoOpCrudEventPublisher<Dividend>;
