//! Event handler trait for Dividend events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DividendEvent;

/// Event handler for Dividend events.
/// Implement this trait to react to Dividend lifecycle events.
pub trait DividendEventHandler: EventHandler<DividendEvent> {}
