//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod dividend_events;
pub mod dividend_event_handlers;
pub mod share_class_events;
pub mod share_class_event_handlers;
pub mod shareholder_events;
pub mod shareholder_event_handlers;
pub mod share_transaction_events;
pub mod share_transaction_event_handlers;

pub use dividend_events::{DividendEvent, DividendEventPublisher, NoopDividendEventPublisher};
pub use dividend_event_handlers::DividendEventHandler;
pub use share_class_events::{ShareClassEvent, ShareClassEventPublisher, NoopShareClassEventPublisher};
pub use share_class_event_handlers::ShareClassEventHandler;
pub use shareholder_events::{ShareholderEvent, ShareholderEventPublisher, NoopShareholderEventPublisher};
pub use shareholder_event_handlers::ShareholderEventHandler;
pub use share_transaction_events::{ShareTransactionEvent, ShareTransactionEventPublisher, NoopShareTransactionEventPublisher};
pub use share_transaction_event_handlers::ShareTransactionEventHandler;

// <<< CUSTOM
// END CUSTOM
