//! Event handler trait for ShareClass events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ShareClassEvent;

/// Event handler for ShareClass events.
/// Implement this trait to react to ShareClass lifecycle events.
pub trait ShareClassEventHandler: EventHandler<ShareClassEvent> {}
