//! Event handler trait for Shareholder events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ShareholderEvent;

/// Event handler for Shareholder events.
/// Implement this trait to react to Shareholder lifecycle events.
pub trait ShareholderEventHandler: EventHandler<ShareholderEvent> {}
