//! Event handler trait for ShareTransaction events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ShareTransactionEvent;

/// Event handler for ShareTransaction events.
/// Implement this trait to react to ShareTransaction lifecycle events.
pub trait ShareTransactionEventHandler: EventHandler<ShareTransactionEvent> {}
