//! Domain events for ShareClass entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ShareClass;

/// Domain events for ShareClass — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ShareClass>)` variant.
pub type ShareClassEvent = CrudEvent<ShareClass>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ShareClass events.
pub type ShareClassEventPublisher = Arc<dyn CrudEventPublisher<ShareClass> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopShareClassEventPublisher = NoOpCrudEventPublisher<ShareClass>;
