//! Domain events for ShareTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ShareTransaction;

/// Domain events for ShareTransaction — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ShareTransaction>)` variant.
pub type ShareTransactionEvent = CrudEvent<ShareTransaction>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ShareTransaction events.
pub type ShareTransactionEventPublisher = Arc<dyn CrudEventPublisher<ShareTransaction> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopShareTransactionEventPublisher = NoOpCrudEventPublisher<ShareTransaction>;
