//! Domain events for Shareholder entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Shareholder;

/// Domain events for Shareholder — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Shareholder>)` variant.
pub type ShareholderEvent = CrudEvent<Shareholder>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Shareholder events.
pub type ShareholderEventPublisher = Arc<dyn CrudEventPublisher<Shareholder> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopShareholderEventPublisher = NoOpCrudEventPublisher<Shareholder>;
