//! Event subscriber type aliases for Equity module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::DividendEvent;
use crate::domain::event::ShareClassEvent;
use crate::domain::event::ShareholderEvent;
use crate::domain::event::ShareTransactionEvent;

/// Subscriber for Dividend events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type DividendEventSubscriber = GenericEventSubscriber<DividendEvent>;

/// Subscriber for ShareClass events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ShareClassEventSubscriber = GenericEventSubscriber<ShareClassEvent>;

/// Subscriber for Shareholder events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ShareholderEventSubscriber = GenericEventSubscriber<ShareholderEvent>;

/// Subscriber for ShareTransaction events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ShareTransactionEventSubscriber = GenericEventSubscriber<ShareTransactionEvent>;

// <<< CUSTOM
// END CUSTOM
