//! ShareTransaction seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ShareTransaction data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SHARETRANSACTION SEEDER
// ============================================================================

/// Seeder for share_transaction
pub struct SeedShareTransactionSeeder;

impl SeedShareTransactionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedShareTransactionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedShareTransactionSeeder {
    fn name(&self) -> &'static str {
        "SeedShareTransactionSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if equity.share_transactions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM equity.share_transactions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/share_transaction_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM equity.share_transactions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

