//! ShareClass seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ShareClass data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SHARECLASS SEEDER
// ============================================================================

/// Seeder for share_class
pub struct SeedShareClassSeeder;

impl SeedShareClassSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedShareClassSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedShareClassSeeder {
    fn name(&self) -> &'static str {
        "SeedShareClassSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if equity.share_classes table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM equity.share_classes")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/share_class_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM equity.share_classes")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

