//! Repository trait for Dividend aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Dividend aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Dividend, DividendStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DividendPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DividendPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DividendPaginatedResult {
    pub data: Vec<Dividend>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DividendFilter {
    pub company_id: Option<Uuid>,
    pub share_class_id: Option<Uuid>,
    pub status: Option<DividendStatus>,
    pub retained_earnings_account_id: Option<Uuid>,
    pub dividend_payable_account_id: Option<Uuid>,
}

impl DividendFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.share_class_id.is_some() || self.status.is_some() || self.retained_earnings_account_id.is_some() || self.dividend_payable_account_id.is_some()
    }
}

/// Repository trait for Dividend aggregate
///
/// This trait defines the persistence contract for Dividend entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DividendRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new dividend entity
    async fn save(&self, entity: &Dividend) -> Result<Dividend>;

    /// Find dividend by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Dividend>>;

    /// Find all dividend entities
    async fn find_all(&self) -> Result<Vec<Dividend>>;

    /// Update dividend by ID
    async fn update(&self, id: &str, entity: &Dividend) -> Result<Option<Dividend>>;

    /// Delete dividend by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List dividend with pagination
    async fn list(&self, params: DividendPaginationParams) -> Result<DividendPaginatedResult>;

    /// List dividend with pagination and filters
    async fn list_with_filters(&self, params: DividendPaginationParams, filters: DividendFilter) -> Result<DividendPaginatedResult>;

    /// Count all dividend entities
    async fn count(&self) -> Result<u64>;

    /// Count dividend entities matching filters
    async fn count_with_filters(&self, filters: DividendFilter) -> Result<u64>;

    /// Check if dividend exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete dividend by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted dividend by ID
    async fn restore(&self, id: &str) -> Result<Option<Dividend>>;

    /// List soft-deleted dividend entities
    async fn list_deleted(&self, params: DividendPaginationParams) -> Result<DividendPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save dividend entities
    async fn bulk_save(&self, entities: &[Dividend]) -> Result<Vec<Dividend>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
