//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod dividend_repository;
pub mod share_class_repository;
pub mod shareholder_repository;
pub mod share_transaction_repository;

// Re-exports
pub use dividend_repository::{
    DividendRepository,
    DividendPaginationParams,
    DividendPaginatedResult,
    DividendFilter,
};
pub use share_class_repository::{
    ShareClassRepository,
    ShareClassPaginationParams,
    ShareClassPaginatedResult,
    ShareClassFilter,
};
pub use shareholder_repository::{
    ShareholderRepository,
    ShareholderPaginationParams,
    ShareholderPaginatedResult,
    ShareholderFilter,
};
pub use share_transaction_repository::{
    ShareTransactionRepository,
    ShareTransactionPaginationParams,
    ShareTransactionPaginatedResult,
    ShareTransactionFilter,
};
