//! Repository trait for Shareholder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Shareholder aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Shareholder, HolderType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareholderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ShareholderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ShareholderPaginatedResult {
    pub data: Vec<Shareholder>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareholderFilter {
    pub company_id: Option<Uuid>,
    pub party_id: Option<Uuid>,
    pub name: Option<String>,
    pub holder_type: Option<HolderType>,
}

impl ShareholderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.party_id.is_some() || self.name.is_some() || self.holder_type.is_some()
    }
}

/// Repository trait for Shareholder aggregate
///
/// This trait defines the persistence contract for Shareholder entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ShareholderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new shareholder entity
    async fn save(&self, entity: &Shareholder) -> Result<Shareholder>;

    /// Find shareholder by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Shareholder>>;

    /// Find all shareholder entities
    async fn find_all(&self) -> Result<Vec<Shareholder>>;

    /// Update shareholder by ID
    async fn update(&self, id: &str, entity: &Shareholder) -> Result<Option<Shareholder>>;

    /// Delete shareholder by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List shareholder with pagination
    async fn list(&self, params: ShareholderPaginationParams) -> Result<ShareholderPaginatedResult>;

    /// List shareholder with pagination and filters
    async fn list_with_filters(&self, params: ShareholderPaginationParams, filters: ShareholderFilter) -> Result<ShareholderPaginatedResult>;

    /// Count all shareholder entities
    async fn count(&self) -> Result<u64>;

    /// Count shareholder entities matching filters
    async fn count_with_filters(&self, filters: ShareholderFilter) -> Result<u64>;

    /// Check if shareholder exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete shareholder by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted shareholder by ID
    async fn restore(&self, id: &str) -> Result<Option<Shareholder>>;

    /// List soft-deleted shareholder entities
    async fn list_deleted(&self, params: ShareholderPaginationParams) -> Result<ShareholderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save shareholder entities
    async fn bulk_save(&self, entities: &[Shareholder]) -> Result<Vec<Shareholder>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
