//! Repository trait for ShareClass aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ShareClass aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ShareClass;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareClassPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ShareClassPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ShareClassPaginatedResult {
    pub data: Vec<ShareClass>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareClassFilter {
    pub company_id: Option<Uuid>,
    pub code: Option<String>,
    pub name: Option<String>,
    pub currency: Option<String>,
    pub share_capital_account_id: Option<Uuid>,
    pub share_premium_account_id: Option<Uuid>,
    pub is_active: Option<bool>,
}

impl ShareClassFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.code.is_some() || self.name.is_some() || self.currency.is_some() || self.share_capital_account_id.is_some() || self.share_premium_account_id.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for ShareClass aggregate
///
/// This trait defines the persistence contract for ShareClass entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ShareClassRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new share_class entity
    async fn save(&self, entity: &ShareClass) -> Result<ShareClass>;

    /// Find share_class by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ShareClass>>;

    /// Find all share_class entities
    async fn find_all(&self) -> Result<Vec<ShareClass>>;

    /// Update share_class by ID
    async fn update(&self, id: &str, entity: &ShareClass) -> Result<Option<ShareClass>>;

    /// Delete share_class by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List share_class with pagination
    async fn list(&self, params: ShareClassPaginationParams) -> Result<ShareClassPaginatedResult>;

    /// List share_class with pagination and filters
    async fn list_with_filters(&self, params: ShareClassPaginationParams, filters: ShareClassFilter) -> Result<ShareClassPaginatedResult>;

    /// Count all share_class entities
    async fn count(&self) -> Result<u64>;

    /// Count share_class entities matching filters
    async fn count_with_filters(&self, filters: ShareClassFilter) -> Result<u64>;

    /// Check if share_class exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete share_class by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted share_class by ID
    async fn restore(&self, id: &str) -> Result<Option<ShareClass>>;

    /// List soft-deleted share_class entities
    async fn list_deleted(&self, params: ShareClassPaginationParams) -> Result<ShareClassPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save share_class entities
    async fn bulk_save(&self, entities: &[ShareClass]) -> Result<Vec<ShareClass>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
