//! Repository trait for ShareTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ShareTransaction aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ShareTransaction, ShareTxnType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareTransactionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ShareTransactionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ShareTransactionPaginatedResult {
    pub data: Vec<ShareTransaction>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ShareTransactionFilter {
    pub company_id: Option<Uuid>,
    pub share_class_id: Option<Uuid>,
    pub shareholder_id: Option<Uuid>,
    pub txn_type: Option<ShareTxnType>,
    pub counterparty_shareholder_id: Option<Uuid>,
    pub transfer_group_id: Option<Uuid>,
    pub posting_reference: Option<String>,
    pub gl_posted: Option<bool>,
}

impl ShareTransactionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.share_class_id.is_some() || self.shareholder_id.is_some() || self.txn_type.is_some() || self.counterparty_shareholder_id.is_some() || self.transfer_group_id.is_some() || self.posting_reference.is_some() || self.gl_posted.is_some()
    }
}

/// Repository trait for ShareTransaction aggregate
///
/// This trait defines the persistence contract for ShareTransaction entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ShareTransactionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new share_transaction entity
    async fn save(&self, entity: &ShareTransaction) -> Result<ShareTransaction>;

    /// Find share_transaction by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ShareTransaction>>;

    /// Find all share_transaction entities
    async fn find_all(&self) -> Result<Vec<ShareTransaction>>;

    /// Update share_transaction by ID
    async fn update(&self, id: &str, entity: &ShareTransaction) -> Result<Option<ShareTransaction>>;

    /// Delete share_transaction by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List share_transaction with pagination
    async fn list(&self, params: ShareTransactionPaginationParams) -> Result<ShareTransactionPaginatedResult>;

    /// List share_transaction with pagination and filters
    async fn list_with_filters(&self, params: ShareTransactionPaginationParams, filters: ShareTransactionFilter) -> Result<ShareTransactionPaginatedResult>;

    /// Count all share_transaction entities
    async fn count(&self) -> Result<u64>;

    /// Count share_transaction entities matching filters
    async fn count_with_filters(&self, filters: ShareTransactionFilter) -> Result<u64>;

    /// Check if share_transaction exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete share_transaction by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted share_transaction by ID
    async fn restore(&self, id: &str) -> Result<Option<ShareTransaction>>;

    /// List soft-deleted share_transaction entities
    async fn list_deleted(&self, params: ShareTransactionPaginationParams) -> Result<ShareTransactionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save share_transaction entities
    async fn bulk_save(&self, entities: &[ShareTransaction]) -> Result<Vec<ShareTransaction>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
