//! Repository for Dividend entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Dividend SQL — the declaration insert and the settlement's
//! compare-and-set claim (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Dividend, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Dividend;

/// Table name for Dividend entities
pub const TABLE_NAME: &str = "equity.dividends";

/// Repository for Dividend entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DividendRepository(
    backbone_orm::GenericCrudRepository<Dividend, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DividendRepository {
    type Target = backbone_orm::GenericCrudRepository<Dividend, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DividendRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a dividend declaration writes.
///
/// `status` is not a field — the INSERT hard-codes `'declared'`. `shares_outstanding` is the SNAPSHOT
/// the declaration was computed against, not a live read.
pub struct NewDividendRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub share_class_id: Uuid,
    pub declaration_date: NaiveDate,
    pub per_share_amount: Decimal,
    pub shares_outstanding: Decimal,
    pub total_amount: Decimal,
    pub retained_earnings_account_id: Uuid,
    pub dividend_payable_account_id: Uuid,
}

/// A dividend's settlement state — what `pay_dividend` needs to settle the payable.
pub struct DividendPaymentRow {
    pub company_id: Uuid,
    pub total_amount: Decimal,
    pub status: String,
    pub dividend_payable_account_id: Uuid,
}

/// The basis a dividend's per-holder split is computed from.
pub struct DividendBasisRow {
    pub company_id: Uuid,
    pub share_class_id: Uuid,
    pub per_share_amount: Decimal,
}

/// Hand-written Dividend SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl DividendRepository {
    /// Record a dividend declaration as `declared`.
    ///
    /// Takes the CALLER'S connection so the declaration and its outbox stage commit as one unit. The
    /// caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_dividend(
        &self,
        conn: &mut sqlx::PgConnection,
        d: &NewDividendRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO equity.dividends
                 (id, company_id, share_class_id, declaration_date, per_share_amount, shares_outstanding,
                  total_amount, status, retained_earnings_account_id, dividend_payable_account_id)
               VALUES ($1,$2,$3,$4,$5,$6,$7,'declared'::dividend_status,$8,$9)"#,
        )
        .bind(d.id).bind(d.company_id).bind(d.share_class_id).bind(d.declaration_date)
        .bind(d.per_share_amount).bind(d.shares_outstanding).bind(d.total_amount)
        .bind(d.retained_earnings_account_id).bind(d.dividend_payable_account_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a dividend's settlement state. `Ok(None)` = not found.
    ///
    /// ID-only: identified by the dividend id alone — no company argument. The read rides the
    /// request-dedicated connection (which carries the caller's `app.company_id`), so another
    /// company's dividend is simply not found. The company read off this row is what the caller then
    /// binds onto the settlement tx.
    pub async fn fetch_for_payment(
        &self,
        pool: &PgPool,
        dividend_id: Uuid,
    ) -> Result<Option<DividendPaymentRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, total_amount, status::text AS status, dividend_payable_account_id
                   FROM equity.dividends WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(dividend_id),
        )
        .await?;
        Ok(row.map(|r| DividendPaymentRow {
            company_id: r.get("company_id"),
            total_amount: r.get("total_amount"),
            status: r.get("status"),
            dividend_payable_account_id: r.get("dividend_payable_account_id"),
        }))
    }

    /// Claim a dividend for settlement: compare-and-set `declared → paid`. Returns the number of rows
    /// affected — the caller treats anything but exactly 1 as "already paid" and rolls back, which is
    /// what stops a concurrent pay from double-remitting.
    ///
    /// Takes the CALLER'S connection: the claim must commit with the outbox stage, and roll back with
    /// it if the GL rejects the posting (leaving the dividend `declared`). The caller has already
    /// bound the company on it — don't re-bind here.
    pub async fn claim_payment(
        &self,
        conn: &mut sqlx::PgConnection,
        dividend_id: Uuid,
        payment_date: NaiveDate,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE equity.dividends SET status='paid'::dividend_status, payment_date=$2
               WHERE id=$1 AND status='declared'::dividend_status"#,
        )
        .bind(dividend_id).bind(payment_date)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Read the basis a dividend's per-holder split is computed from. `Ok(None)` = not found. ID-only
    /// + scoped read — see [`Self::fetch_for_payment`].
    pub async fn fetch_allocation_basis(
        &self,
        pool: &PgPool,
        dividend_id: Uuid,
    ) -> Result<Option<DividendBasisRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, share_class_id, per_share_amount
                   FROM equity.dividends WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(dividend_id),
        )
        .await?;
        Ok(row.map(|r| DividendBasisRow {
            company_id: r.get("company_id"),
            share_class_id: r.get("share_class_id"),
            per_share_amount: r.get("per_share_amount"),
        }))
    }
}

backbone_core::impl_crud_repository!(DividendRepository, Dividend, soft_delete);
