//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod dividend_repository;
mod share_class_repository;
mod shareholder_repository;
mod share_transaction_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use dividend_repository::DividendRepository;
pub use share_class_repository::ShareClassRepository;
pub use shareholder_repository::ShareholderRepository;
pub use share_transaction_repository::ShareTransactionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
