//! Repository for ShareClass entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ShareClass SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::ShareClass;

/// Table name for ShareClass entities
pub const TABLE_NAME: &str = "equity.share_classes";

/// Repository for ShareClass entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShareClassRepository(
    backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShareClassRepository {
    type Target = backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ShareClassRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a share-class registration writes.
///
/// `is_active` is not a field — the INSERT hard-codes `true`.
pub struct NewShareClassRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub code: &'a str,
    pub name: &'a str,
    pub par_value: Decimal,
    pub currency: &'a str,
    pub share_capital_account_id: Uuid,
    pub share_premium_account_id: Uuid,
}

/// A share class's terms: the par value capital is booked at, the accounts capital and premium land
/// in, and whether the class still accepts movements.
pub struct ShareClassDetailRow {
    pub par_value: Decimal,
    pub share_capital_account_id: Uuid,
    pub share_premium_account_id: Uuid,
    pub is_active: bool,
}

/// Hand-written ShareClass SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ShareClassRepository {
    /// Register a share class.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company
    /// is on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence (a bare-pool
    /// insert is rejected).
    pub async fn insert_share_class(
        &self,
        pool: &PgPool,
        c: &NewShareClassRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO equity.share_classes
                     (id, company_id, code, name, par_value, currency, share_capital_account_id,
                      share_premium_account_id, is_active)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,true)"#,
            )
            .bind(c.id).bind(c.company_id).bind(c.code).bind(c.name).bind(c.par_value)
            .bind(c.currency).bind(c.share_capital_account_id).bind(c.share_premium_account_id),
        )
        .await?;
        Ok(())
    }

    /// Load a share class's terms. `Ok(None)` = not found.
    ///
    /// ID-only: the class is identified by id alone — no company argument, and this read runs BEFORE
    /// the caller's transaction is bound. It therefore rides the ambient scope: under HTTP the
    /// request-dedicated connection carries the caller's `app.company_id`, so another company's class
    /// is simply not found. A non-request caller (job, event subscriber) MUST wrap this in
    /// `with_company_scope(Some(company_id))`.
    pub async fn fetch_class(
        &self,
        pool: &PgPool,
        id: Uuid,
    ) -> Result<Option<ShareClassDetailRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT par_value, currency, share_capital_account_id, share_premium_account_id, is_active
                   FROM equity.share_classes WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(id),
        )
        .await?;
        Ok(row.map(|r| ShareClassDetailRow {
            par_value: r.get("par_value"),
            share_capital_account_id: r.get("share_capital_account_id"),
            share_premium_account_id: r.get("share_premium_account_id"),
            is_active: r.get("is_active"),
        }))
    }
}

backbone_core::impl_crud_repository!(ShareClassRepository, ShareClass, soft_delete);
