//! Repository for Shareholder entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Shareholder SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Shareholder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Shareholder;

/// Table name for Shareholder entities
pub const TABLE_NAME: &str = "equity.shareholders";

/// Repository for Shareholder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShareholderRepository(
    backbone_orm::GenericCrudRepository<Shareholder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShareholderRepository {
    type Target = backbone_orm::GenericCrudRepository<Shareholder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ShareholderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a shareholder registration writes.
///
/// Mirrors the raw column shape rather than the `Shareholder` entity: `holder_type` binds as `&str`
/// and is cast at the DB (`$5::holder_type`), so a bad value fails as a DB error rather than a
/// deserialize panic.
pub struct NewShareholderRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub party_id: Option<Uuid>,
    pub name: &'a str,
    pub holder_type: &'a str,
}

/// Hand-written Shareholder SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl ShareholderRepository {
    /// Register a shareholder.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company
    /// is on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    pub async fn insert_shareholder(
        &self,
        pool: &PgPool,
        s: &NewShareholderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO equity.shareholders (id, company_id, party_id, name, holder_type)
                   VALUES ($1,$2,$3,$4,$5::holder_type)"#,
            )
            .bind(s.id).bind(s.company_id).bind(s.party_id).bind(s.name).bind(s.holder_type),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(ShareholderRepository, Shareholder, soft_delete);
