//! Repository for ShareClass entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ShareClass;

/// Table name for ShareClass entities
pub const TABLE_NAME: &str = "equity.share_classes";

/// Repository for ShareClass entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShareClassRepository(
    backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShareClassRepository {
    type Target = backbone_orm::GenericCrudRepository<ShareClass, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ShareClassRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ShareClassRepository, ShareClass, soft_delete);
