//! Repository for ShareTransaction entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ShareTransaction SQL: the register's movement inserts, the
//! per-(class,holder) position lock, and the register's TWO aggregation rules (4-layer rule: services
//! orchestrate, repos hold SQL).
//!
//! Tenancy (ADR-0029): the SQL here carries no tenant key. The pool reads ride the request-dedicated
//! connection when the composing service bound one (its fence variables govern what the RLS layer
//! accepts) and fall back to a plain pool read otherwise.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ShareTransaction, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::ShareTransaction;

/// Table name for ShareTransaction entities
pub const TABLE_NAME: &str = "equity.share_transactions";

/// Repository for ShareTransaction entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShareTransactionRepository(
    backbone_orm::GenericCrudRepository<ShareTransaction, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShareTransactionRepository {
    type Target = backbone_orm::GenericCrudRepository<ShareTransaction, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ShareTransactionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an issue movement writes. `txn_type` and `gl_posted` are not fields — the INSERT
/// hard-codes `'issue'` and `true` (the journal is posted before this row is written).
pub struct NewIssueTxnRow<'a> {
    pub id: Uuid,
    pub share_class_id: Uuid,
    pub shareholder_id: Uuid,
    pub quantity: Decimal,
    pub price_per_share: Decimal,
    pub amount: Decimal,
    pub posting_reference: Option<&'a str>,
    pub txn_date: NaiveDate,
}

/// The exact row ONE leg of a transfer writes.
///
/// A transfer is two rows sharing a `transfer_group_id`. `price_per_share`/`amount` are not fields —
/// the INSERT hard-codes `0`: a transfer moves ownership, not money, and posts no journal
/// (`gl_posted` is hard-coded `false`). `txn_type` binds as `&str` and is cast at the DB
/// (`$4::share_txn_type`).
pub struct NewTransferLegRow<'a> {
    pub id: Uuid,
    pub share_class_id: Uuid,
    /// The holder this leg moves shares for.
    pub shareholder_id: Uuid,
    /// `transfer_out` or `transfer_in`.
    pub txn_type: &'a str,
    pub quantity: Decimal,
    /// The OTHER holder in the transfer.
    pub counterparty_shareholder_id: Uuid,
    /// Ties the two legs together.
    pub transfer_group_id: Uuid,
    pub txn_date: NaiveDate,
}

/// The exact row a buyback movement writes. `txn_type`/`gl_posted` are hard-coded `'buyback'`/`true`.
pub struct NewBuybackTxnRow {
    pub id: Uuid,
    pub share_class_id: Uuid,
    pub shareholder_id: Uuid,
    pub quantity: Decimal,
    pub price_per_share: Decimal,
    pub amount: Decimal,
    pub txn_date: NaiveDate,
}

/// One holder's position in a class, as aggregated by the cap-table read.
pub struct HoldingRow {
    pub shareholder_id: Uuid,
    pub quantity: Decimal,
}

/// Hand-written ShareTransaction SQL. Lives here (not in the write service) per the module's 4-layer
/// rule. The register applies TWO different aggregation rules — a holder POSITION (issue/transfer_in
/// +, buyback/transfer_out −) and SHARES OUTSTANDING (issue +, buyback −, transfers net out across
/// holders). Both sign rules live only here.
impl ShareTransactionRepository {
    /// Record an issue movement.
    ///
    /// Takes the CALLER'S connection so the movement and its outbox stage commit as one unit. The
    /// caller has already propagated the ambient request scope onto it (`bind_org_scope_on`,
    /// relay-only) — don't re-bind here.
    pub async fn insert_issue(
        &self,
        conn: &mut sqlx::PgConnection,
        i: &NewIssueTxnRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO equity.share_transactions
                 (id, share_class_id, shareholder_id, txn_type, quantity, price_per_share, amount,
                  posting_reference, txn_date, gl_posted)
               VALUES ($1,$2,$3,'issue'::share_txn_type,$4,$5,$6,$7,$8,true)"#,
        )
        .bind(i.id)
        .bind(i.share_class_id)
        .bind(i.shareholder_id)
        .bind(i.quantity)
        .bind(i.price_per_share)
        .bind(i.amount)
        .bind(i.posting_reference)
        .bind(i.txn_date)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Record ONE leg of a transfer. Both legs must be written on the same tx, or the register would
    /// hold a half-transfer. Same caller-owned-tx contract as [`Self::insert_issue`].
    pub async fn insert_transfer_leg(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewTransferLegRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO equity.share_transactions
                 (id, share_class_id, shareholder_id, txn_type, quantity, price_per_share,
                  amount, counterparty_shareholder_id, transfer_group_id, txn_date, gl_posted)
               VALUES ($1,$2,$3,$4::share_txn_type,$5,0,0,$6,$7,$8,false)"#,
        )
        .bind(t.id)
        .bind(t.share_class_id)
        .bind(t.shareholder_id)
        .bind(t.txn_type)
        .bind(t.quantity)
        .bind(t.counterparty_shareholder_id)
        .bind(t.transfer_group_id)
        .bind(t.txn_date)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Record a buyback movement. Same caller-owned-tx contract as [`Self::insert_issue`].
    pub async fn insert_buyback(
        &self,
        conn: &mut sqlx::PgConnection,
        b: &NewBuybackTxnRow,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO equity.share_transactions
                 (id, share_class_id, shareholder_id, txn_type, quantity, price_per_share, amount,
                  txn_date, gl_posted)
               VALUES ($1,$2,$3,'buyback'::share_txn_type,$4,$5,$6,$7,true)"#,
        )
        .bind(b.id)
        .bind(b.share_class_id)
        .bind(b.shareholder_id)
        .bind(b.quantity)
        .bind(b.price_per_share)
        .bind(b.amount)
        .bind(b.txn_date)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Take a per-(class, holder) advisory xact lock — serializes concurrent removals so a
    /// [`Self::holding`] check and the movement insert that follows are atomic against another remover.
    /// The holding is a SUM with no single row to lock, so an advisory lock is the guard. Ids are
    /// globally unique, so the (class, holder) pair needs no tenant column (ADR-0029).
    ///
    /// Takes the CALLER'S connection: an xact lock is released at commit, so it MUST be taken on the
    /// same transaction that writes the movement.
    pub async fn lock_position(
        &self,
        conn: &mut sqlx::PgConnection,
        class_id: Uuid,
        holder_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))")
            .bind(format!("{class_id}:{holder_id}"))
            .execute(conn)
            .await?;
        Ok(())
    }

    /// A holder's current position in a class = Σ (issue/transfer_in) − Σ (buyback/transfer_out).
    ///
    /// Takes the CALLER'S connection: this is the bounds check, and it must read under the same
    /// transaction (and the same [`Self::lock_position`] lock) as the movement it guards.
    pub async fn holding(
        &self,
        conn: &mut sqlx::PgConnection,
        class_id: Uuid,
        holder_id: Uuid,
    ) -> Result<Decimal, sqlx::Error> {
        sqlx::query_scalar(
            r#"SELECT COALESCE(SUM(CASE WHEN txn_type IN ('issue','transfer_in') THEN quantity ELSE -quantity END),0)
               FROM equity.share_transactions
               WHERE share_class_id=$1 AND shareholder_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(class_id).bind(holder_id)
        .fetch_one(conn)
        .await
    }

    /// Shares outstanding for a class = Σ issued − Σ bought back (transfers net to zero across holders).
    ///
    /// Runs on the pool through the tenant-agnostic scoped read: it rides the request-dedicated
    /// connection when the composing service bound one — under a decorated deployment a bare-pool
    /// read would land on a fresh connection with no fence variables and return 0, which would read
    /// as a real "no shares outstanding" and wrongly refuse every dividend — and falls back to a
    /// plain pool read otherwise.
    pub async fn shares_outstanding(
        &self,
        pool: &PgPool,
        class_id: Uuid,
    ) -> Result<Decimal, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT COALESCE(SUM(CASE WHEN txn_type='issue' THEN quantity
                                            WHEN txn_type='buyback' THEN -quantity ELSE 0 END),0) AS outstanding
                   FROM equity.share_transactions
                   WHERE share_class_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(class_id),
        )
        .await?;
        // COALESCE guarantees exactly one row.
        Ok(row.map(|r| r.get("outstanding")).unwrap_or(Decimal::ZERO))
    }

    /// Every holder's non-zero position in a class, largest first.
    ///
    /// Runs on the pool through `fetch_all_rows_scoped`: it rides the request-dedicated connection
    /// when the composing service bound one — under a decorated deployment a bare-pool read would
    /// land on a fresh connection with no fence variables and return nothing — and falls back to a
    /// plain pool read otherwise. (The legacy company_scope helper's task-local branch is never
    /// taken: a stripped module sets no legacy scope. The tenant-agnostic `org_scope` module has no
    /// fetch-all twin yet; when it gains one, this call should move to it.)
    pub async fn holdings(
        &self,
        pool: &PgPool,
        class_id: Uuid,
    ) -> Result<Vec<HoldingRow>, sqlx::Error> {
        let rows = backbone_orm::company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT shareholder_id,
                          COALESCE(SUM(CASE WHEN txn_type IN ('issue','transfer_in') THEN quantity ELSE -quantity END),0) AS qty
                   FROM equity.share_transactions
                   WHERE share_class_id=$1 AND (metadata->>'deleted_at') IS NULL
                   GROUP BY shareholder_id HAVING
                     COALESCE(SUM(CASE WHEN txn_type IN ('issue','transfer_in') THEN quantity ELSE -quantity END),0) <> 0
                   ORDER BY qty DESC"#,
            )
            .bind(class_id),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| HoldingRow {
                shareholder_id: r.get("shareholder_id"),
                quantity: r.get("qty"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(ShareTransactionRepository, ShareTransaction, soft_delete);
