//! Validator for Dividend entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Dividend>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::Dividend;

/// Validator type alias for Dividend entities.
pub type DividendValidator = EntityValidator<Dividend>;

/// Build a validator for Dividend with all schema-defined field rules.
pub fn dividend_validator() -> DividendValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
