//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod dividend_validator;
pub mod share_class_validator;
pub mod shareholder_validator;
pub mod share_transaction_validator;

pub use dividend_validator::{DividendValidator, dividend_validator};
pub use share_class_validator::{ShareClassValidator, share_class_validator};
pub use shareholder_validator::{ShareholderValidator, shareholder_validator};
pub use share_transaction_validator::{ShareTransactionValidator, share_transaction_validator};

// <<< CUSTOM
// END CUSTOM
