//! Validator for Shareholder entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Shareholder>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Shareholder;

/// Validator type alias for Shareholder entities.
pub type ShareholderValidator = EntityValidator<Shareholder>;

/// Build a validator for Shareholder with all schema-defined field rules.
pub fn shareholder_validator() -> ShareholderValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Shareholder| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
