//! Validator for ShareTransaction entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ShareTransaction>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::ShareTransaction;

/// Validator type alias for ShareTransaction entities.
pub type ShareTransactionValidator = EntityValidator<ShareTransaction>;

/// Build a validator for ShareTransaction with all schema-defined field rules.
pub fn share_transaction_validator() -> ShareTransactionValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("posting_reference", |e: &ShareTransaction| e.posting_reference.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
