//! Validator for ShareClass entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ShareClass>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::ShareClass;

/// Validator type alias for ShareClass entities.
pub type ShareClassValidator = EntityValidator<ShareClass>;

/// Build a validator for ShareClass with all schema-defined field rules.
pub fn share_class_validator() -> ShareClassValidator {
    EntityValidator::new()
        .rule(RequiredString::new("code", |e: &ShareClass| &e.code))
        .rule(RequiredString::new("name", |e: &ShareClass| &e.name))
        .rule(RequiredString::new("currency", |e: &ShareClass| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
