//! Auth configuration for Dividend handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Dividend>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DividendService;
use crate::domain::entity::Dividend;

/// Permission string constants for Dividend operations.
pub mod permissions {
    pub const LIST:        &str = "dividend:list";
    pub const READ:        &str = "dividend:read";
    pub const CREATE:      &str = "dividend:create";
    pub const UPDATE:      &str = "dividend:update";
    pub const DELETE:      &str = "dividend:delete";
    pub const RESTORE:     &str = "dividend:restore";
    pub const TRASH:       &str = "dividend:trash";
    pub const EMPTY_TRASH: &str = "dividend:empty_trash";
    pub const BULK_CREATE: &str = "dividend:bulk_create";
    pub const UPSERT:      &str = "dividend:upsert";
}

/// Resource policy for Dividend — maps CRUD actions to permission strings.
pub struct DividendPolicy;

#[async_trait]
impl ResourcePolicy<Dividend> for DividendPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Dividend,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Dividend handlers.
///
/// Wraps `DividendService` and checks `DividendPolicy` before delegating.
pub type DividendGuard = PermissionGuard<Dividend>;

/// Service-integrated permission guard for Dividend (for use in generated handlers).
pub type DividendServiceGuard = ServicePermissionGuard<Dividend, DividendService, DividendPolicy>;

// <<< CUSTOM
// END CUSTOM
