//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod dividend_auth;
pub mod share_class_auth;
pub mod shareholder_auth;
pub mod share_transaction_auth;

pub use dividend_auth::{DividendPolicy, DividendGuard, DividendServiceGuard};
pub use share_class_auth::{ShareClassPolicy, ShareClassGuard, ShareClassServiceGuard};
pub use shareholder_auth::{ShareholderPolicy, ShareholderGuard, ShareholderServiceGuard};
pub use share_transaction_auth::{ShareTransactionPolicy, ShareTransactionGuard, ShareTransactionServiceGuard};

// <<< CUSTOM
// END CUSTOM
