//! Auth configuration for Shareholder handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Shareholder>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ShareholderService;
use crate::domain::entity::Shareholder;

/// Permission string constants for Shareholder operations.
pub mod permissions {
    pub const LIST:        &str = "shareholder:list";
    pub const READ:        &str = "shareholder:read";
    pub const CREATE:      &str = "shareholder:create";
    pub const UPDATE:      &str = "shareholder:update";
    pub const DELETE:      &str = "shareholder:delete";
    pub const RESTORE:     &str = "shareholder:restore";
    pub const TRASH:       &str = "shareholder:trash";
    pub const EMPTY_TRASH: &str = "shareholder:empty_trash";
    pub const BULK_CREATE: &str = "shareholder:bulk_create";
    pub const UPSERT:      &str = "shareholder:upsert";
}

/// Resource policy for Shareholder — maps CRUD actions to permission strings.
pub struct ShareholderPolicy;

#[async_trait]
impl ResourcePolicy<Shareholder> for ShareholderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Shareholder,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Shareholder handlers.
///
/// Wraps `ShareholderService` and checks `ShareholderPolicy` before delegating.
pub type ShareholderGuard = PermissionGuard<Shareholder>;

/// Service-integrated permission guard for Shareholder (for use in generated handlers).
pub type ShareholderServiceGuard = ServicePermissionGuard<Shareholder, ShareholderService, ShareholderPolicy>;

// <<< CUSTOM
// END CUSTOM
