//! Auth configuration for ShareTransaction handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ShareTransaction>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ShareTransactionService;
use crate::domain::entity::ShareTransaction;

/// Permission string constants for ShareTransaction operations.
pub mod permissions {
    pub const LIST:        &str = "share_transaction:list";
    pub const READ:        &str = "share_transaction:read";
    pub const CREATE:      &str = "share_transaction:create";
    pub const UPDATE:      &str = "share_transaction:update";
    pub const DELETE:      &str = "share_transaction:delete";
    pub const RESTORE:     &str = "share_transaction:restore";
    pub const TRASH:       &str = "share_transaction:trash";
    pub const EMPTY_TRASH: &str = "share_transaction:empty_trash";
    pub const BULK_CREATE: &str = "share_transaction:bulk_create";
    pub const UPSERT:      &str = "share_transaction:upsert";
}

/// Resource policy for ShareTransaction — maps CRUD actions to permission strings.
pub struct ShareTransactionPolicy;

#[async_trait]
impl ResourcePolicy<ShareTransaction> for ShareTransactionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ShareTransaction,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ShareTransaction handlers.
///
/// Wraps `ShareTransactionService` and checks `ShareTransactionPolicy` before delegating.
pub type ShareTransactionGuard = PermissionGuard<ShareTransaction>;

/// Service-integrated permission guard for ShareTransaction (for use in generated handlers).
pub type ShareTransactionServiceGuard = ServicePermissionGuard<ShareTransaction, ShareTransactionService, ShareTransactionPolicy>;

// <<< CUSTOM
// END CUSTOM
