//! Auth configuration for ShareClass handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ShareClass>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ShareClassService;
use crate::domain::entity::ShareClass;

/// Permission string constants for ShareClass operations.
pub mod permissions {
    pub const LIST:        &str = "share_class:list";
    pub const READ:        &str = "share_class:read";
    pub const CREATE:      &str = "share_class:create";
    pub const UPDATE:      &str = "share_class:update";
    pub const DELETE:      &str = "share_class:delete";
    pub const RESTORE:     &str = "share_class:restore";
    pub const TRASH:       &str = "share_class:trash";
    pub const EMPTY_TRASH: &str = "share_class:empty_trash";
    pub const BULK_CREATE: &str = "share_class:bulk_create";
    pub const UPSERT:      &str = "share_class:upsert";
}

/// Resource policy for ShareClass — maps CRUD actions to permission strings.
pub struct ShareClassPolicy;

#[async_trait]
impl ResourcePolicy<ShareClass> for ShareClassPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ShareClass,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ShareClass handlers.
///
/// Wraps `ShareClassService` and checks `ShareClassPolicy` before delegating.
pub type ShareClassGuard = PermissionGuard<ShareClass>;

/// Service-integrated permission guard for ShareClass (for use in generated handlers).
pub type ShareClassServiceGuard = ServicePermissionGuard<ShareClass, ShareClassService, ShareClassPolicy>;

// <<< CUSTOM
// END CUSTOM
