//! Dividend API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Dividend CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DIVIDEND TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Dividend
pub struct DividendTestData;

impl TestDataGenerator for DividendTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "share_class_id": Uuid::new_v4().to_string(),
            "declaration_date": Utc::now().format("%Y-%m-%d").to_string(),
            "payment_date": null,
            "per_share_amount": 0,
            "shares_outstanding": 0,
            "total_amount": 0,
            "status": "declared",
            "retained_earnings_account_id": Uuid::new_v4().to_string(),
            "dividend_payable_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "share_class_id": Uuid::new_v4().to_string(),
            "declaration_date": Utc::now().format("%Y-%m-%d").to_string(),
            "payment_date": null,
            "per_share_amount": 0,
            "shares_outstanding": 0,
            "total_amount": 0,
            "status": "declared",
            "retained_earnings_account_id": Uuid::new_v4().to_string(),
            "dividend_payable_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/share_classes", &super::share_class_api_test::ShareClassTestData).await {
            deps.push(("share_class_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// DIVIDEND API TEST
// ============================================================================

/// Dividend API test suite
pub struct DividendApiTest {
    inner: GenericCrudTest<DividendTestData>,
}

impl DividendApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/dividends", "Dividend");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DividendTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DividendApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_dividend_crud() {
        let mut test = DividendApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Dividend specific tests here
// <<< CUSTOM TESTS END >>>
