//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod dividend_api_test;
pub mod share_class_api_test;
pub mod shareholder_api_test;
pub mod share_transaction_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use dividend_api_test::*;
pub use share_class_api_test::*;
pub use shareholder_api_test::*;
pub use share_transaction_api_test::*;
