//! ShareClass API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ShareClass CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SHARECLASS TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ShareClass
pub struct ShareClassTestData;

impl TestDataGenerator for ShareClassTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "par_value": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "share_capital_account_id": Uuid::new_v4().to_string(),
            "share_premium_account_id": Uuid::new_v4().to_string(),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "par_value": 0,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "share_capital_account_id": Uuid::new_v4().to_string(),
            "share_premium_account_id": Uuid::new_v4().to_string(),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SHARECLASS API TEST
// ============================================================================

/// ShareClass API test suite
pub struct ShareClassApiTest {
    inner: GenericCrudTest<ShareClassTestData>,
}

impl ShareClassApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/share_classes", "ShareClass");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ShareClassTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ShareClassApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_share_class_crud() {
        let mut test = ShareClassApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ShareClass specific tests here
// <<< CUSTOM TESTS END >>>
