//! ShareTransaction API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ShareTransaction CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SHARETRANSACTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ShareTransaction
pub struct ShareTransactionTestData;

impl TestDataGenerator for ShareTransactionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "share_class_id": Uuid::new_v4().to_string(),
            "shareholder_id": Uuid::new_v4().to_string(),
            "txn_type": "issue",
            "quantity": 0,
            "price_per_share": 0,
            "amount": 0,
            "counterparty_shareholder_id": null,
            "transfer_group_id": null,
            "posting_reference": null,
            "txn_date": Utc::now().format("%Y-%m-%d").to_string(),
            "gl_posted": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "share_class_id": Uuid::new_v4().to_string(),
            "shareholder_id": Uuid::new_v4().to_string(),
            "txn_type": "issue",
            "quantity": 0,
            "price_per_share": 0,
            "amount": 0,
            "counterparty_shareholder_id": null,
            "transfer_group_id": null,
            "posting_reference": null,
            "txn_date": Utc::now().format("%Y-%m-%d").to_string(),
            "gl_posted": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/share_classes", &super::share_class_api_test::ShareClassTestData).await {
            deps.push(("share_class_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/shareholders", &super::shareholder_api_test::ShareholderTestData).await {
            deps.push(("shareholder_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SHARETRANSACTION API TEST
// ============================================================================

/// ShareTransaction API test suite
pub struct ShareTransactionApiTest {
    inner: GenericCrudTest<ShareTransactionTestData>,
}

impl ShareTransactionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/share_transactions", "ShareTransaction");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ShareTransactionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ShareTransactionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_share_transaction_crud() {
        let mut test = ShareTransactionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ShareTransaction specific tests here
// <<< CUSTOM TESTS END >>>
