//! Equity Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::DividendService;
use crate::application::service::ShareClassService;
use crate::application::service::ShareholderService;
use crate::application::service::ShareTransactionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Dividend service
    pub dividend_service: Arc<DividendService>,
    /// ShareClass service
    pub share_class_service: Arc<ShareClassService>,
    /// Shareholder service
    pub shareholder_service: Arc<ShareholderService>,
    /// ShareTransaction service
    pub share_transaction_service: Arc<ShareTransactionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        dividend_service: Arc<DividendService>,
        share_class_service: Arc<ShareClassService>,
        shareholder_service: Arc<ShareholderService>,
        share_transaction_service: Arc<ShareTransactionService>
    ) -> Self {
        Self {
            dividend_service,
            share_class_service,
            shareholder_service,
            share_transaction_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::EquityModule) -> Self {
        Self {
            dividend_service: module.dividend_service.clone(),
            share_class_service: module.share_class_service.clone(),
            shareholder_service: module.shareholder_service.clone(),
            share_transaction_service: module.share_transaction_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    dividend_service: Option<Arc<DividendService>>,
    share_class_service: Option<Arc<ShareClassService>>,
    shareholder_service: Option<Arc<ShareholderService>>,
    share_transaction_service: Option<Arc<ShareTransactionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Dividend service.
    pub fn with_dividend_service(mut self, service: Arc<DividendService>) -> Self {
        self.dividend_service = Some(service);
        self
    }

    /// Set the ShareClass service.
    pub fn with_share_class_service(mut self, service: Arc<ShareClassService>) -> Self {
        self.share_class_service = Some(service);
        self
    }

    /// Set the Shareholder service.
    pub fn with_shareholder_service(mut self, service: Arc<ShareholderService>) -> Self {
        self.shareholder_service = Some(service);
        self
    }

    /// Set the ShareTransaction service.
    pub fn with_share_transaction_service(mut self, service: Arc<ShareTransactionService>) -> Self {
        self.share_transaction_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            dividend_service: self.dividend_service.expect("dividend_service is required"),
            share_class_service: self.share_class_service.expect("share_class_service is required"),
            shareholder_service: self.shareholder_service.expect("shareholder_service is required"),
            share_transaction_service: self.share_transaction_service.expect("share_transaction_service is required"),
        }
    }
}
