//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    dividend_handler::create_dividend_routes,
    share_class_handler::create_share_class_routes,
    shareholder_handler::create_shareholder_routes,
    share_transaction_handler::create_share_transaction_routes,
};

use crate::application::service::{
    DividendService,
    ShareClassService,
    ShareholderService,
    ShareTransactionService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub dividend: Arc<DividendService>,
    pub share_class: Arc<ShareClassService>,
    pub shareholder: Arc<ShareholderService>,
    pub share_transaction: Arc<ShareTransactionService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Dividend routes (12 Backbone endpoints)
        .merge(create_dividend_routes(services.dividend))
        // ShareClass routes (12 Backbone endpoints)
        .merge(create_share_class_routes(services.share_class))
        // Shareholder routes (12 Backbone endpoints)
        .merge(create_shareholder_routes(services.shareholder))
        // ShareTransaction routes (12 Backbone endpoints)
        .merge(create_share_transaction_routes(services.share_transaction))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn dividend_routes(service: Arc<DividendService>) -> Router {
        create_dividend_routes(service)
    }

    pub fn share_class_routes(service: Arc<ShareClassService>) -> Router {
        create_share_class_routes(service)
    }

    pub fn shareholder_routes(service: Arc<ShareholderService>) -> Router {
        create_shareholder_routes(service)
    }

    pub fn share_transaction_routes(service: Arc<ShareTransactionService>) -> Router {
        create_share_transaction_routes(service)
    }

}
