//! Public events for Equity module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// DIVIDEND EVENTS
// ============================================================================

/// Event published when a Dividend is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DividendCreatedEvent {
    pub id: DividendId,
    pub data: DividendDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Dividend is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DividendUpdatedEvent {
    pub id: DividendId,
    pub data: DividendDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Dividend is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DividendDeletedEvent {
    pub id: DividendId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SHARECLASS EVENTS
// ============================================================================

/// Event published when a ShareClass is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareClassCreatedEvent {
    pub id: ShareClassId,
    pub data: ShareClassDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShareClass is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareClassUpdatedEvent {
    pub id: ShareClassId,
    pub data: ShareClassDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShareClass is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareClassDeletedEvent {
    pub id: ShareClassId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SHAREHOLDER EVENTS
// ============================================================================

/// Event published when a Shareholder is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareholderCreatedEvent {
    pub id: ShareholderId,
    pub data: ShareholderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Shareholder is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareholderUpdatedEvent {
    pub id: ShareholderId,
    pub data: ShareholderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Shareholder is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareholderDeletedEvent {
    pub id: ShareholderId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SHARETRANSACTION EVENTS
// ============================================================================

/// Event published when a ShareTransaction is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareTransactionCreatedEvent {
    pub id: ShareTransactionId,
    pub data: ShareTransactionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShareTransaction is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareTransactionUpdatedEvent {
    pub id: ShareTransactionId,
    pub data: ShareTransactionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ShareTransaction is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShareTransactionDeletedEvent {
    pub id: ShareTransactionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Equity module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EquityEvent {
    DividendCreated(DividendCreatedEvent),
    DividendUpdated(DividendUpdatedEvent),
    DividendDeleted(DividendDeletedEvent),
    ShareClassCreated(ShareClassCreatedEvent),
    ShareClassUpdated(ShareClassUpdatedEvent),
    ShareClassDeleted(ShareClassDeletedEvent),
    ShareholderCreated(ShareholderCreatedEvent),
    ShareholderUpdated(ShareholderUpdatedEvent),
    ShareholderDeleted(ShareholderDeletedEvent),
    ShareTransactionCreated(ShareTransactionCreatedEvent),
    ShareTransactionUpdated(ShareTransactionUpdatedEvent),
    ShareTransactionDeleted(ShareTransactionDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EquityEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for EquityEventMetadata {
    fn default() -> Self {
        Self {
            module: "equity",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
