//! Equity Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Equity exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use equity::exports::{DividendDto, EquityQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `DividendDto` - Data transfer object for Dividend
/// - `DividendSummary` - Summary view of Dividend
/// - `DividendId` - Type-safe ID wrapper
/// - `ShareClassDto` - Data transfer object for ShareClass
/// - `ShareClassSummary` - Summary view of ShareClass
/// - `ShareClassId` - Type-safe ID wrapper
/// - `ShareholderDto` - Data transfer object for Shareholder
/// - `ShareholderSummary` - Summary view of Shareholder
/// - `ShareholderId` - Type-safe ID wrapper
/// - `ShareTransactionDto` - Data transfer object for ShareTransaction
/// - `ShareTransactionSummary` - Summary view of ShareTransaction
/// - `ShareTransactionId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `EquityQueryService` - Read-only queries
///
/// ## Public Events
/// - `DividendCreatedEvent` - Published when Dividend is created
/// - `DividendUpdatedEvent` - Published when Dividend is updated
/// - `DividendDeletedEvent` - Published when Dividend is deleted
/// - `ShareClassCreatedEvent` - Published when ShareClass is created
/// - `ShareClassUpdatedEvent` - Published when ShareClass is updated
/// - `ShareClassDeletedEvent` - Published when ShareClass is deleted
/// - `ShareholderCreatedEvent` - Published when Shareholder is created
/// - `ShareholderUpdatedEvent` - Published when Shareholder is updated
/// - `ShareholderDeletedEvent` - Published when Shareholder is deleted
/// - `ShareTransactionCreatedEvent` - Published when ShareTransaction is created
/// - `ShareTransactionUpdatedEvent` - Published when ShareTransaction is updated
/// - `ShareTransactionDeletedEvent` - Published when ShareTransaction is deleted
pub struct ExportSummary;
