//! Public services for Equity module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Intended read-only contract for other modules.
//!
//! CAUTION — not yet a realized contract: `EquityQueryService` below is declared but NOT implemented
//! in-tree, and the validated/event-sourced write surface (`EquityWriteService`) is un-composed (no
//! service drives it). Both are gated behind the `unstable-write-service` feature; the crate's default
//! public surface is generic CRUD. Do not assume "writes go through events" — today writes are generic
//! CRUD rows unless a composing service mounts the guarded router.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Equity module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
/// Un-composed read contract: declared but not implemented in-tree. Gated behind
/// `unstable-write-service` until a composing backend-service provides an `impl`.
#[cfg(feature = "unstable-write-service")]
#[async_trait]
pub trait EquityQueryService: Send + Sync {
    /// Get Dividend by ID
    async fn get_dividend(&self, id: DividendId) -> Result<Option<DividendDto>>;

    /// Get Dividend summary by ID
    async fn get_dividend_summary(&self, id: DividendId) -> Result<Option<DividendSummary>>;

    /// Check if Dividend exists
    async fn dividend_exists(&self, id: DividendId) -> Result<bool>;

    /// Get ShareClass by ID
    async fn get_share_class(&self, id: ShareClassId) -> Result<Option<ShareClassDto>>;

    /// Get ShareClass summary by ID
    async fn get_share_class_summary(&self, id: ShareClassId) -> Result<Option<ShareClassSummary>>;

    /// Check if ShareClass exists
    async fn share_class_exists(&self, id: ShareClassId) -> Result<bool>;

    /// Get Shareholder by ID
    async fn get_shareholder(&self, id: ShareholderId) -> Result<Option<ShareholderDto>>;

    /// Get Shareholder summary by ID
    async fn get_shareholder_summary(&self, id: ShareholderId) -> Result<Option<ShareholderSummary>>;

    /// Check if Shareholder exists
    async fn shareholder_exists(&self, id: ShareholderId) -> Result<bool>;

    /// Get ShareTransaction by ID
    async fn get_share_transaction(&self, id: ShareTransactionId) -> Result<Option<ShareTransactionDto>>;

    /// Get ShareTransaction summary by ID
    async fn get_share_transaction_summary(&self, id: ShareTransactionId) -> Result<Option<ShareTransactionSummary>>;

    /// Check if ShareTransaction exists
    async fn share_transaction_exists(&self, id: ShareTransactionId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of EquityQueryService
pub struct EquityQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> EquityQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
