//! Equity Module — cap table + equity accounting (shareholders, share classes, share transactions,
//! dividends).
//!
//! ## What this crate ships by default
//!
//! Generic CRUD over the four entities, mounted via [`EquityModule::all_crud_routes`]. That surface is
//! **unguarded**: a well-formed request can write a row the domain would forbid (e.g. soft-delete a
//! `Shareholder` a transaction still references, or insert a register movement that drives a holding
//! negative). It is intended for trusted/admin/seeding contexts only — compose a guarded router for any
//! real deployment.
//!
//! ## What is NOT yet a committed contract
//!
//! The hand-authored cap-table write surface (`EquityWriteService`: issue / transfer / buyback /
//! dividend, with its GL port and lifecycle events) and the read contract (`EquityQueryService`) are
//! **un-composed** — no in-workspace service constructs the write service, injects its sinks, implements
//! the query trait, or mounts the guarded router. They are gated behind the `unstable-write-service`
//! Cargo feature and exist for tests + a future composing service, not for dependents today.
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Domain entity structs are intentionally NOT re-exported at the crate root — they are the storage
// representation, not this module's contract. Depend on the DTOs in `exports::` instead. (The validated
// write surface lives under `application::service::equity_*`, gated behind `unstable-write-service`.)

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::DividendService;
pub use application::service::ShareClassService;
pub use application::service::ShareholderService;
pub use application::service::ShareTransactionService;

// Re-exports - Workflows (Example saga scaffolding; not a committed surface — opt in via the feature).
#[cfg(feature = "unstable-write-service")]
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Equity module configuration.
///
/// By default this module exposes **generic CRUD** over the four entities via
/// [`EquityModule::all_crud_routes`] — an unguarded surface for trusted/admin/seeding contexts.
///
/// The validated, event-sourced cap-table write surface (`EquityWriteService`) and the read contract
/// (`EquityQueryService`) are **un-composed**: no in-workspace service drives them yet. They are gated
/// behind the `unstable-write-service` feature and are not part of the committed contract.
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let equity = EquityModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = equity.all_crud_routes();
/// ```
pub struct EquityModule {
    pub dividend_service: Arc<DividendService>,
    pub share_class_service: Arc<ShareClassService>,
    pub shareholder_service: Arc<ShareholderService>,
    pub share_transaction_service: Arc<ShareTransactionService>,
}

impl EquityModule {
    /// Create a new module builder
    pub fn builder() -> EquityModuleBuilder {
        EquityModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_dividend_routes,
            create_share_class_routes,
            create_shareholder_routes,
            create_share_transaction_routes,
        };

        Router::new()
            .merge(create_dividend_routes(self.dividend_service.clone()))
            .merge(create_share_class_routes(self.share_class_service.clone()))
            .merge(create_shareholder_routes(self.shareholder_service.clone()))
            .merge(create_share_transaction_routes(self.share_transaction_service.clone()))
    }

}

/// Builder for EquityModule
pub struct EquityModuleBuilder {
    db_pool: Option<PgPool>,
}

impl EquityModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<EquityModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Dividend service
        let dividend_repository = Arc::new(DividendRepository::new(db_pool.clone()));
        let dividend_service = Arc::new(DividendService::with_repository(dividend_repository.clone()));

        // ShareClass service
        let share_class_repository = Arc::new(ShareClassRepository::new(db_pool.clone()));
        let share_class_service = Arc::new(ShareClassService::with_repository(share_class_repository.clone()));

        // Shareholder service
        let shareholder_repository = Arc::new(ShareholderRepository::new(db_pool.clone()));
        let shareholder_service = Arc::new(ShareholderService::with_repository(shareholder_repository.clone()));

        // ShareTransaction service
        let share_transaction_repository = Arc::new(ShareTransactionRepository::new(db_pool.clone()));
        let share_transaction_service = Arc::new(ShareTransactionService::with_repository(share_transaction_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(EquityModule {
            dividend_service,
            share_class_service,
            shareholder_service,
            share_transaction_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for EquityModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
