//! Use case type aliases for Dividend aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDividendDto, UpdateDividendDto};
use crate::application::service::DividendService;
use crate::domain::entity::Dividend;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDividendUseCase = CreateUseCase<Dividend, CreateDividendDto, DividendService>;
pub type UpdateDividendUseCase = UpdateUseCase<Dividend, UpdateDividendDto, DividendService>;
pub type GetDividendUseCase    = GetUseCase<Dividend, DividendService>;
pub type DeleteDividendUseCase = DeleteUseCase<Dividend, DividendService>;
pub type ListDividendUseCase   = ListUseCase<Dividend, DividendService>;

// <<< CUSTOM
// END CUSTOM
