//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod dividend_usecases;
pub mod share_class_usecases;
pub mod shareholder_usecases;
pub mod share_transaction_usecases;

pub use dividend_usecases::{
    CreateDividendUseCase, UpdateDividendUseCase, GetDividendUseCase,
    DeleteDividendUseCase, ListDividendUseCase,
};
pub use share_class_usecases::{
    CreateShareClassUseCase, UpdateShareClassUseCase, GetShareClassUseCase,
    DeleteShareClassUseCase, ListShareClassUseCase,
};
pub use shareholder_usecases::{
    CreateShareholderUseCase, UpdateShareholderUseCase, GetShareholderUseCase,
    DeleteShareholderUseCase, ListShareholderUseCase,
};
pub use share_transaction_usecases::{
    CreateShareTransactionUseCase, UpdateShareTransactionUseCase, GetShareTransactionUseCase,
    DeleteShareTransactionUseCase, ListShareTransactionUseCase,
};

// <<< CUSTOM
// END CUSTOM
