//! Use case type aliases for ShareClass aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateShareClassDto, UpdateShareClassDto};
use crate::application::service::ShareClassService;
use crate::domain::entity::ShareClass;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateShareClassUseCase = CreateUseCase<ShareClass, CreateShareClassDto, ShareClassService>;
pub type UpdateShareClassUseCase = UpdateUseCase<ShareClass, UpdateShareClassDto, ShareClassService>;
pub type GetShareClassUseCase    = GetUseCase<ShareClass, ShareClassService>;
pub type DeleteShareClassUseCase = DeleteUseCase<ShareClass, ShareClassService>;
pub type ListShareClassUseCase   = ListUseCase<ShareClass, ShareClassService>;

// <<< CUSTOM
// END CUSTOM
