//! Use case type aliases for ShareTransaction aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateShareTransactionDto, UpdateShareTransactionDto};
use crate::application::service::ShareTransactionService;
use crate::domain::entity::ShareTransaction;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateShareTransactionUseCase = CreateUseCase<ShareTransaction, CreateShareTransactionDto, ShareTransactionService>;
pub type UpdateShareTransactionUseCase = UpdateUseCase<ShareTransaction, UpdateShareTransactionDto, ShareTransactionService>;
pub type GetShareTransactionUseCase    = GetUseCase<ShareTransaction, ShareTransactionService>;
pub type DeleteShareTransactionUseCase = DeleteUseCase<ShareTransaction, ShareTransactionService>;
pub type ListShareTransactionUseCase   = ListUseCase<ShareTransaction, ShareTransactionService>;

// <<< CUSTOM
// END CUSTOM
