//! Use case type aliases for Shareholder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateShareholderDto, UpdateShareholderDto};
use crate::application::service::ShareholderService;
use crate::domain::entity::Shareholder;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateShareholderUseCase = CreateUseCase<Shareholder, CreateShareholderDto, ShareholderService>;
pub type UpdateShareholderUseCase = UpdateUseCase<Shareholder, UpdateShareholderDto, ShareholderService>;
pub type GetShareholderUseCase    = GetUseCase<Shareholder, ShareholderService>;
pub type DeleteShareholderUseCase = DeleteUseCase<Shareholder, ShareholderService>;
pub type ListShareholderUseCase   = ListUseCase<Shareholder, ShareholderService>;

// <<< CUSTOM
// END CUSTOM
