//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod dividend_handler;
pub mod share_class_handler;
pub mod shareholder_handler;
pub mod share_transaction_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use dividend_handler::{create_dividend_routes, create_dividend_read_routes, create_dividend_write_routes};
pub use share_class_handler::{create_share_class_routes, create_share_class_read_routes, create_share_class_write_routes};
pub use shareholder_handler::{create_shareholder_routes, create_shareholder_read_routes, create_shareholder_write_routes};
pub use share_transaction_handler::{create_share_transaction_routes, create_share_transaction_read_routes, create_share_transaction_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_equity_routes;
// END CUSTOM